services:  
  
  ch_server:  
    image: clickhouse/clickhouse-server:24.8.4  
    ports:  
      - "8123:8123"  
    environment:  
      CLICKHOUSE_USER: ${CLICKHOUSE_USER} 
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}